name: dart_dot_reporter
description: Dot test reporter for Dart & Flutter & Human. Makes test results clear from the high-level view.
version: 2.0.0
homepage: https://github.com/apastuhov/dart_dot_reporter
repository: https://github.com/apastuhov/dart_dot_reporter

environment:
  sdk: ^3.5.4

executables:
  dart_dot_reporter: dart_dot_reporter

# Add regular dependencies here.
#dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
